version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: phonenumber-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: phonenumber-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
